---
apiVersion: v1
kind: Service
metadata:
  labels:
    expose: "true"
    run: tm-ui
  name: tm-ui
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: tm-ui
  sessionAffinity: None
